export const AUTHENTICATION_MANAGER = Symbol('AUTHENTICATION_MANAGER');
export const TOKEN_VALIDATION_CLIENT = Symbol('TOKEN_VALIDATION_CLIENT');
export const MOVIE_RESERVATION_REPOSITORY = Symbol(
  'MOVIE_RESERVATION_REPOSITORY',
);
