export const AUTHENTICATION_MANAGER = Symbol('AUTHENTICATION_MANAGER');
export const TOKEN_VALIDATION_CLIENT = Symbol('TOKEN_VALIDATION_CLIENT');
export const MOVIE_RESERVATION_REPOSITORY = Symbol(
  'MOVIE_RESERVATION_REPOSITORY',
);
export const RESERVATION_REQUEST_PROCESSOR = Symbol(
  'RESERVATION_REQUEST_PROCESSOR',
);
export const RESERVATION_REQUEST_WORK_REPOSITORY = Symbol(
  'RESERVATION_REQUEST_WORK_REPOSITORY',
);
export const RESERVATION_WORKER_OPTIONS = Symbol('RESERVATION_WORKER_OPTIONS');
export const IN_MEMORY_MOVIE_RESERVATION_STORE = Symbol(
  'IN_MEMORY_MOVIE_RESERVATION_STORE',
);
export const POSTGRES_KNEX = Symbol('POSTGRES_KNEX');
export const RESERVATION_ID_GENERATOR = Symbol('RESERVATION_ID_GENERATOR');
export const RESERVATION_REQUEST_ID_GENERATOR = Symbol(
  'RESERVATION_REQUEST_ID_GENERATOR',
);
export const CLOCK = Symbol('CLOCK');
